site_name: CCA Guide

repo_name: twangodev/cca
repo_url: https://github.com/twangodev/cca
edit_uri: edit/main/docs/

site_author: James Ding
site_url: https://cca.twango.dev
site_description: A handy guide and reference for students at California Crosspoint Academy.

nav:
  - Home: index.md
  - AP Calculus BC:
    - Assignments:
      - Limits Review: ap-calculus-bc/assignments/limits-review.pdf
    - Take Home Quizzes:
      - Quiz 1: ap-calculus-bc/take-home-quiz/quiz-1.md
      - Quiz 2: ap-calculus-bc/take-home-quiz/quiz-2.md
      - Quiz 3: ap-calculus-bc/take-home-quiz/quiz-3.md
      - Quiz 4: ap-calculus-bc/take-home-quiz/quiz-4.md
  - AP Computer Science:
    - Blue Pelican Java: ap-computer-science/blue-pelican-java.pdf
    - Introduction to Java: ap-computer-science/introduction-to-java.md
    - Variables: ap-computer-science/variables.md
    - Scanner: ap-computer-science/scanner.md
    - Logical Operators: ap-computer-science/logical-operators.md
    - Type Casting: ap-computer-science/type-casting.md
    - Random: ap-computer-science/random.md
    - Time Complexity: ap-computer-science/time-complexity.md
    - Loops: ap-computer-science/loops.md
    - Commenting: ap-computer-science/commenting.md
    - Strings and Characters: ap-computer-science/strings-and-characters.md
    - Number Systems: ap-computer-science/number-systems.md
    - Methods: ap-computer-science/methods.md
    - Recursion: ap-computer-science/recursion.md
    - Object Oriented Programming: ap-computer-science/object-oriented-programming.md
    - Arrays: ap-computer-science/arrays.md
    - Logic: ap-computer-science/logic.md
  - AP Language:
    - Classwork:
      - Analyzing Visual Texts: ap-language/classwork/analyzing-visual-texts.md
      - Andrew Toles Washington Post: ap-language/classwork/andrew-toles-washington-post.md
      - Barbie is Past Saving: ap-language/classwork/barbie-is-past-saving.md
      - Bauerlein The Dumbest Generation: ap-language/classwork/bauerlein-the-dumbest-generation.md
      - BLK History Month: ap-language/classwork/blk-history-month.md
      - Clinton Concession Speech: ap-language/classwork/clinton-concession-speech.md
      - College Claims of Value: ap-language/classwork/college-claims-of-value.md
      - Conceding Arguments Turkle: ap-language/classwork/conceding-arguments-turkle.md
      - Concept of Love: ap-language/classwork/concept-of-love.md
      - Cost of College Synthesis Timed Write: ap-language/classwork/cost-of-college-synthesis-timed-write.md
      - Damar Hamlin: ap-language/classwork/damar-hamlin.md
      - Dumpster Diving Notes: ap-language/classwork/dumpster-diving-notes.md
      - Exercises in Specificity: ap-language/classwork/exercises-in-specificity.md
      - Felons Voting Counterclaim: ap-language/classwork/felons-voting-counterclaim.md
      - Felons Right to Vote Timed Write: ap-language/classwork/felons-right-to-vote-timed-write.md
      - Felons Voting Counterclaim: ap-language/classwork/felons-voting-counterclaim.md
      - FRQ 2013 2: ap-language/classwork/frq-2013-2.md
      - FRQ Unit 3: ap-language/classwork/frq-unit-3.md
      - Ground Zero Mosque Speech: ap-language/classwork/ground-zero-mosque-speech.md
      - Kristoff Response: ap-language/classwork/kristoff-response.md
      - Lou Gehrigs Farewell Speech: ap-language/classwork/lou-gehrigs-farewell-speech.md
      - Love Essay: ap-language/classwork/love-essay.md
      - Malcolm X Rhetorical Situation: ap-language/classwork/malcolm-x-rhetorical-situation.md
      - Next Level Barbie Evaluation: ap-language/classwork/next-level-barbie-evaluation.md
      - Overrated FRQ: ap-language/classwork/overrated-frq.md
      - Practice Argumentative Essay: ap-language/classwork/practice-argumentative-essay.md
      - Practice Rhetorical Analysis: ap-language/classwork/practice-rhetorical-analysis.md
      - Practice Synthesis: ap-language/classwork/practice-synthesis.md
      - Pure Comedy Line of Reasoning: ap-language/classwork/pure-comedy-line-of-reasoning.md
      - Sanders Free College: ap-language/classwork/sanders-free-college.md
      - Serving in Florida: ap-language/classwork/serving-in-florida.md
      - Sonia Sotomayor: ap-language/classwork/sonia-sotomayor.md
      - Space Exploration Counter Argument: ap-language/classwork/space-exploration-counter-argument.md
      - Superheroes Killed the Movie Star: ap-language/classwork/superheroes-killed-the-movie-star.md
      - Suzanne Berne Where Nothing Says Everything: ap-language/classwork/suzanne-berne-where-nothing-says-everything.md
      - Technology Education Quick Write: ap-language/classwork/technology-education-quick-write.md
      - Thesis Practice: ap-language/classwork/thesis-practice.md
      - Toulmin Model: ap-language/classwork/toulmin-model.md
      - Unpaid College Athletes: ap-language/classwork/unpaid-college-athletes.md
    - Homework:
      - Abdul Jabbar: ap-language/homework/abdul-jabbar.md
      - Analyzing Sources: ap-language/homework/analyzing-sources.md
      - Apophasis RAPS: ap-language/homework/apophasis-raps.md
      - Appositives Practice: ap-language/homework/appositives-practice.md
      - Believing Game: ap-language/homework/believing-game.md
      - Boxing Day: ap-language/homework/boxing-day.md
      - British Art Snots are Working in the Dark: ap-language/homework/british-art-snots-are-working-in-the-dark.md
      - Brooker T Washington Rhetorical Situation: ap-language/homework/brooker-t-washington-rhetorical-situation.md
      - Cesar Chavez: ap-language/homework/cesar-chavez.md
      - Class RAPS: ap-language/homework/class-raps.md
      - Colorblind Environmentalism: ap-language/homework/colorblind-environmentalism.md
      - Declarative of Independence: ap-language/homework/declarative-of-independence.md
      - Direct Precise Active Passive: ap-language/homework/direct-precise-active-passive.md
      - Dog Refugee Analysis: ap-language/homework/dog-refugee-analysis.md
      - Dumpster Diving Claims Counterarguments: ap-language/homework/dumpster-diving-claims-counterarguments.md
      - Dumpster Diving Word Association: ap-language/homework/dumpster-diving-word-association.md
      - Einstein Dear Phyllis Letter: ap-language/homework/einstein-dear-phyllis-letter.md
      - Establishing Ethos Differentiating Audiences: ap-language/homework/establishing-ethos-differentiating-audiences.md
      - Free College 2 Years: ap-language/homework/free-college-2-years.md
      - Gospel of Wealth: ap-language/homework/gospel-of-wealth.md
      - Ground Zero Mosque Speech: ap-language/homework/ground-zero-mosque-speech.md
      - Have We Lost Sight of the Promise: ap-language/homework/have-we-lost-sight-of-the-promise.md
      - Henry Louis Gates Jr Restoring Black History: ap-language/homework/henry-louis-gates-jr-restoring-black-history.md
      - I Know Why the Caged Bird Cannot Read: ap-language/homework/i-know-why-the-caged-bird-cannot-read.md
      - Investing in Fast Food: ap-language/homework/investing-in-fast-food.md
      - James Baldwin Talk to Teachers: ap-language/homework/james-baldwin-talk-to-teachers.md
      - Justice Vengeance Tarantino: ap-language/homework/justice-vengeance-tarantino.md
      - Letter to Gopnik: ap-language/homework/letter-to-gopnik.md
      - Lincoln Inaugural Address: ap-language/homework/lincoln-inaugural-address.md
      - My First Lifeline Maya Angelou: ap-language/homework/my-first-lifeline-maya-angelou.md
      - No Free College: ap-language/homework/no-free-college.md
      - Oklahoma Bombing Memorial Prayer Service Address: ap-language/homework/oklahoma-bombing-memorial-prayer-service-address.md
      - Onion Girl Moved to Tears: ap-language/homework/onion-girl-moved-to-tears.md
      - Paying College Athletes: ap-language/homework/paying-college-athletes.md
      - Pure Comedy Response: ap-language/homework/pure-comedy-response.md
      - Rhetorical Risks Controversial Image: ap-language/homework/rhetorical-risks-controversial-image.md
      - Rhetorical Strategies: ap-language/homework/rhetorical-strategies.md
      - Serving in Florida: ap-language/homework/serving-in-florida.md
      - Superheroes Movie Stars: ap-language/homework/superheroes-movie-stars.md
      - Syntax Raps: ap-language/homework/syntax-raps.md
      - Synthesis Essay Notes: ap-language/homework/synthesis-essay-notes.md
      - The Hill We Climb: ap-language/homework/the-hill-we-climb.md
      - Toulmin Model Rewrites: ap-language/homework/toulmin-model-rewrites.md
    - Index Cards:
      - Diction: ap-language/index-cards/diction.md
      - Irony: ap-language/index-cards/irony.md
      - Parallelism: ap-language/index-cards/parallelism.md
      - Rhetorical: ap-language/index-cards/rhetorical.md
      - Syntax: ap-language/index-cards/syntax.md
      - Text Arrangement: ap-language/index-cards/text-arrangement.md
      - Tone: ap-language/index-cards/tone.md
    - Rhetoric:
      - What is Rhetoric: ap-language/rhetoric/what-is-rhetoric.md
      - Rhetorical Situation: ap-language/rhetoric/rhetorical-situation.md
      - Rhetoric Triangle: ap-language/rhetoric/rhetoric-triangle.md
      - Ethos Logos Pathos: ap-language/rhetoric/ethos-logos-pathos.md
    - Irony Timed Write: ap-language/irony-timed-write.md
    - Semester 1 Final: ap-language/semester-1-final.md
  - AP Literature:
      - Annotations:
        - Fools Crow: ap-literature/annotations/fools-crow.pdf
      - Assignments:
        - Analyzing Plot Structure: ap-literature/assignments/analyzing-plot-structure.md
        - Characterization of the First Day: ap-literature/assignments/characterization-first-day.md
        - Everyday Use: ap-literature/assignments/everyday-use.md
        - Happiness Claims: ap-literature/assignments/happiness-claims.md
        - Hills Like White Elephants (POV): ap-literature/assignments/hills-like-white-elephants-pov.md
        - Introduction to Poetry - Billy Collins: ap-literature/assignments/introduction-to-poetry-billy-collins.md
        - My Heart and I Analysis: ap-literature/assignments/my-heart-and-i-analysis.md
        - Labor Day - Louise Gluck: ap-literature/assignments/labor-day-louise-gluck.md
        - Liquor Divorce: ap-literature/assignments/liquor-divorce.md
        - Monkey Bridge: ap-literature/assignments/monkey-bridge.md
        - My Yellow Coat: ap-literature/assignments/my-yellow-coat.md
        - Pygmalion Act 2 Lesson Plan: ap-literature/assignments/pygmalion-act-2-lesson-plan.md
        - Solitude Noiseless Patient Spider: ap-literature/assignments/solitude-noiseless-patient-spider.md
        - Walker, Mansfield, Joyce Text: ap-literature/assignments/walker-mansfield-joyce.md
      - Notes:
        - Argumentation: ap-literature/notes/argumentation.md
        - Characters and Plot: ap-literature/notes/characters-and-plot.md
        - Contrast: ap-literature/notes/contrast.md
        - Digging - Seamus Heaney: ap-literature/notes/digging-seamus-heaney.md
        - Fiction: ap-literature/notes/fiction.md
        - Figurative Language: ap-literature/notes/figurative-language.md
        - Narrative Perspective & POV: ap-literature/notes/narrative-perspective-pov.md
        - Poetry: ap-literature/notes/poetry.md
        - Pygmalion: ap-literature/notes/pygmalion.md
        - Shifts: ap-literature/notes/shifts.md
        - Syntax: ap-literature/notes/syntax.md
        - Theme: ap-literature/notes/theme.md
      - Timed Writes:
          - Blind Date - Lydia Davis: ap-literature/timed-writes/blind-date-lydia-davis.md
          - Unit 2 FRQ: ap-literature/timed-writes/unit-2-frq.md
  - AP Statistics:
    - Chapter 1 - Collecting Data in Reasonable Ways: ap-statistics/chapter-1.md
    - Chapter 2 - Graphical Methods for Describing Data Distributions: ap-statistics/chapter-2.md
    - Chapter 3 - Numerical Methods for Describing Data Distributions: ap-statistics/chapter-3.md
    - Chapter 4 - Describing Bivariate Numerical Data: ap-statistics/chapter-4.md
    - Chapter 5 - Probability: ap-statistics/chapter-5.md
    - Chapter 6 - Random Variables and Probability Distributions: ap-statistics/chapter-6.md
    - Chapter 8 - Sampling Variability and Sampling Distributions: ap-statistics/chapter-8.md
    - Chi Square Tests: ap-statistics/chi-squared-tests.md
    - Inference: ap-statistics/inference.md
  - Biology:
    - Unit 1 Ecology:
      - Module 4 Population Ecology:
        - Lesson 1 Progress Check: biology/unit-1-ecology/module-4-population-ecology/lesson-1-progress-check.md
  - Economics:
    - Assignments:
      - Kidney Opportunity Cost: economics/assignments/kidney-opportunity-cost.md
      - Pickleball Supply and Demand: economics/assignments/pickleball-supply-and-demand.md
      - The Road Not Taken: economics/assignments/the-road-not-taken.md
    - Notes:
      - Chapter 1: economics/notes/chapter-1.md
      - Chapter 2: economics/notes/chapter-2.md
      - Chapter 3: economics/notes/chapter-3.md
      - Chapter 4: economics/notes/chapter-4.md
      - Chapter 5: economics/notes/chapter-5.md
    - Study Guide:
      - Chapter 3-4: economics/study-guide/chapter-3-4.md
  - Senior Bible:
    - What If Jesus Was Serious:
      - Intro, 1.1-2: senior-bible/wijws/1.1-1.2.md
      - 1.3 - 1.4: senior-bible/wijws/1.3-1.4.md
      - 1.5 - 1.6: senior-bible/wijws/1.5-1.6.md
      - 1.7 - 1.8: senior-bible/wijws/1.7-1.8.md
      - 1.9 - 2.1: senior-bible/wijws/1.9-2.1.md
      - 2.2 - 2.3: senior-bible/wijws/2.2-2.3.md
      - 2.4 - 2.5: senior-bible/wijws/2.4-2.5.md
    - Personal Collect: senior-bible/personal-collect.md
  - US History:
    - 3 The American Revolution:
      - 1 The French and Indian War: us-history/3-the-american-revolution/1-the-french-and-indian-war.md
      - 2 Causes of the Revolution: us-history/3-the-american-revolution/2-causes-of-the-revolution.md
      - 3 Colonists Declare Independence: us-history/3-the-american-revolution/3-colonists-declare-independence.md
      - 4 Americans Win the Revolution: us-history/3-the-american-revolution/4-americans-win-the-revolution.md
      - Review: us-history/3-the-american-revolution/review.md
    - 4 Establishing the New Nation:
      - 1 Articles of Confederation: us-history/4-establishing-the-new-nation/1-articles-of-confederation.md
    - 5 The Early Republic:
      - 1 The New Government Finds Its Way: us-history/5-the-early-republic/1-the-new-government-finds-its-way.md
      - 2 Jefferson As President: us-history/5-the-early-republic/2-jefferson-as-president.md
    - Classwork:
      - 15.1 Worksheet: us-history/classwork/15.1-worksheet.md
      - Causes of the Civil War: us-history/classwork/causes-of-the-civil-war.md
      - Civic Discussion 1: us-history/classwork/civic-discussion-1.md
      - Civic Discussion 2: us-history/classwork/civic-discussion-2.md
      - General Eisenhower's Two Statements: us-history/classwork/general-eisenhowers-two-statements.md
      - Why I Love a Country That Once Betrayed Me: us-history/classwork/why-i-love-a-country-that-once-betrayed-me.md
    - Homework:
      - Worksheets:
        - 4.2 The Constitutional Convention: us-history/homework/worksheets/4.2-the-constitutional-convention.md
        - 4.3 The Enduring Constitution: us-history/homework/worksheets/4.3-the-enduring-constitution.md
        - 5.6 Nationalism Influences Policies: us-history/homework/worksheets/5.6-nationalism-influences-policies.md
        - 5.7 Jacksonian Democracy: us-history/homework/worksheets/5.7-jacksonian-democracy.md
        - 7.4 African Americans and the War: us-history/homework/worksheets/7.4-african-americans-and-the-war.md
        - 7.5 Everyday Life During the War: us-history/homework/worksheets/7.5-everyday-life-during-the-war.md
        - 10.4 Worksheet: us-history/homework/worksheets/10.4-worksheet.md
        - 11.3 Worksheet: us-history/homework/worksheets/11.3-worksheet.md
        - 11.5 American Influence Grows: us-history/homework/worksheets/11.5-american-influence-grows.md
        - 11.6 The Spanish-American War: us-history/homework/worksheets/11.6-the-spanish-american-war.md
        - 14.1 Rise of Aggressive Dictators: us-history/homework/worksheets/14.1-rise-of-aggressive-dictators.md
        - 15.3 The Cold War Intensifies: us-history/homework/worksheets/15.3-the-cold-war-intensifies.md
        - 15.4 Cold War Fears at Home: us-history/homework/worksheets/15.4-cold-war-fears-at-home.md
      - 13 Readings: us-history/homework/13-readings.md
      - 14 Savaas: us-history/homework/14-savaas.md
      - Frederick Douglass Primary Source Reading: us-history/homework/frederick-douglass-primary-source-reading.md
      - Reconstruction Webquest: us-history/homework/reconstruction-webquest.md
      - Slavery DBQ: us-history/homework/slavery-dbq.md
      - The Civil Rights Era: us-history/homework/the-civil-rights-era.md
      - Vietnam War Webquest: us-history/homework/vietnam-war-webquest.md
theme:
  name: material
  logo: assets/cca.png
  favicon: assets/favicon.ico
  features:
    - toc.follow
    - navigation.top
    - content.code.copy
    - content.action.edit
    - content.action.view
    - navigation.footer
    - content.tabs.link

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - glightbox
  - offline
  - social
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true

markdown_extensions:
  - abbr
  - admonition
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.keys
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true


extra_javascript:
  - javascripts/katex.js
  - javascripts/kotlin.js
  - https://unpkg.com/kotlin-playground@1
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

extra_css:
  - stylesheets/kotlin.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
