site_name: CCA Guide

repo_name: twangodev/cca
repo_url: https://github.com/twangodev/cca
edit_uri: edit/main/docs/

site_url: https://cca.twango.dev
site_description: A handy guide and reference for students at California Crosspoint Academy.

nav:
  - Home: index.md
  - AP Calculus BC:
    - Assignments:
      - Limits Review: ap-calculus-bc/assignments/limits-review.pdf
    - Take Home Quizzes:
      - Quiz 1: ap-calculus-bc/take-home-quiz/quiz-1.md
      - Quiz 2: ap-calculus-bc/take-home-quiz/quiz-2.md
      - Quiz 3: ap-calculus-bc/take-home-quiz/quiz-3.md
      - Quiz 4: ap-calculus-bc/take-home-quiz/quiz-4.md
  - AP Computer Science:
    - Introduction to Java: ap-computer-science/introduction-to-java.md
    - Variables: ap-computer-science/variables.md
    - Scanner: ap-computer-science/scanner.md
    - Logical Operators: ap-computer-science/logical-operators.md
    - Type Casting: ap-computer-science/type-casting.md
    - Random: ap-computer-science/random.md
    - Time Complexity: ap-computer-science/time-complexity.md
    - Loops: ap-computer-science/loops.md
    - Commenting: ap-computer-science/commenting.md
    - Strings and Characters: ap-computer-science/strings-and-characters.md
    - Number Systems: ap-computer-science/number-systems.md
    - Methods: ap-computer-science/methods.md
    - Recursion: ap-computer-science/recursion.md
    - Object Oriented Programming: ap-computer-science/object-oriented-programming.md
    - Arrays: ap-computer-science/arrays.md
    - Logic: ap-computer-science/logic.md
  - AP Language:
    - Irony Timed Write: ap-language/irony-timed-write.md
    - Semester 1 Final: ap-language/semester-1-final.md
  - AP Literature:
      - Annotations:
        - Fools Crow: ap-literature/annotations/fools-crow.pdf
      - Assignments:
        - Analyzing Plot Structure: ap-literature/assignments/analyzing-plot-structure.md
        - Characterization of the First Day: ap-literature/assignments/characterization-first-day.md
        - Everyday Use: ap-literature/assignments/everyday-use.md
        - Happiness Claims: ap-literature/assignments/happiness-claims.md
        - Hills Like White Elephants (POV): ap-literature/assignments/hills-like-white-elephants-pov.md
        - Introduction to Poetry - Billy Collins: ap-literature/assignments/introduction-to-poetry-billy-collins.md
        - My Heart and I Analysis: ap-literature/assignments/my-heart-and-i-analysis.md
        - Labor Day - Louise Gluck: ap-literature/assignments/labor-day-louise-gluck.md
        - Liquor Divorce: ap-literature/assignments/liquor-divorce.md
        - My Yellow Coat: ap-literature/assignments/my-yellow-coat.md
        - Pygmalion Act 2 Lesson Plan: ap-literature/assignments/pygmalion-act-2-lesson-plan.md
        - Solitude Noiseless Patient Spider: ap-literature/assignments/solitude-noiseless-patient-spider.md
        - Walker, Mansfield, Joyce Text: ap-literature/assignments/walker-mansfield-joyce.md
      - Notes:
        - Argumentation: ap-literature/notes/argumentation.md
        - Characters and Plot: ap-literature/notes/characters-and-plot.md
        - Contrast: ap-literature/notes/contrast.md
        - Digging - Seamus Heaney: ap-literature/notes/digging-seamus-heaney.md
        - Fiction: ap-literature/notes/fiction.md
        - Figurative Language: ap-literature/notes/figurative-language.md
        - Narrative Perspective & POV: ap-literature/notes/narrative-perspective-pov.md
        - Poetry: ap-literature/notes/poetry.md
        - Pygmalion: ap-literature/notes/pygmalion.md
        - Shifts: ap-literature/notes/shifts.md
        - Theme: ap-literature/notes/theme.md
      - Timed Writes:
          - Blind Date - Lydia Davis: ap-literature/timed-writes/blind-date-lydia-davis.md
          - Unit 2 FRQ: ap-literature/timed-writes/unit-2-frq.md
  - AP Statistics:
    - Chapter 1 - Collecting Data in Reasonable Ways: ap-statistics/chapter-1.md
    - Chapter 2 - Graphical Methods for Describing Data Distributions: ap-statistics/chapter-2.md
    - Chapter 3 - Numerical Methods for Describing Data Distributions: ap-statistics/chapter-3.md
    - Chapter 4 - Describing Bivariate Numerical Data: ap-statistics/chapter-4.md
    - Chapter 5 - Probability: ap-statistics/chapter-5.md
    - Chapter 6 - Random Variables and Probability Distributions: ap-statistics/chapter-6.md
    - Chapter 8 - Sampling Variability and Sampling Distributions: ap-statistics/chapter-8.md
    - Chi Square Tests: ap-statistics/chi-squared-tests.md
    - Inference: ap-statistics/inference.md
  - Economics:
    - Assignments:
      - Kidney Opportunity Cost: economics/assignments/kidney-opportunity-cost.md
      - The Road Not Taken: economics/assignments/the-road-not-taken.md
    - Notes:
      - Chapter 1: economics/notes/chapter-1.md
      - Chapter 2: economics/notes/chapter-2.md
      - Chapter 3: economics/notes/chapter-3.md
      - Chapter 4: economics/notes/chapter-4.md
  - Senior Bible:
    - What If Jesus Was Serious:
      - Intro, 1.1-2: senior-bible/wijws/1.1-1.2.md
      - 1.3 - 1.4: senior-bible/wijws/1.3-1.4.md
      - 1.5 - 1.6: senior-bible/wijws/1.5-1.6.md
      - 1.7 - 1.8: senior-bible/wijws/1.7-1.8.md
      - 1.9 - 2.1: senior-bible/wijws/1.9-2.1.md
      - 2.2 - 2.3: senior-bible/wijws/2.2-2.3.md
      - 2.4 - 2.5: senior-bible/wijws/2.4-2.5.md
    - Personal Collect: senior-bible/personal-collect.md
  - US History:
    - Worksheets:
      - 4.2 The Constitutional Convention: us-history/worksheets/4.2-the-constitutional-convention.md
      - 4.3 The Enduring Constitution: us-history/worksheets/4.3-the-enduring-constitution.md
      - 5.6 Nationalism Influences Policies: us-history/worksheets/5.6-nationalism-influences-policies.md
      - 5.7 Jacksonian Democracy: us-history/worksheets/5.7-jacksonian-democracy.md
      - 7.4 African Americans and the War: us-history/worksheets/7.4-african-americans-and-the-war.md
      - 7.5 Everyday Life During the War: us-history/worksheets/7.5-everyday-life-during-the-war.md
      - 10.4: us-history/worksheets/10.4-worksheet.md
      - 11.3: us-history/worksheets/11.3-worksheet.md
      - 11.5 American Influence Grows: us-history/worksheets/11.5-american-influence-grows.md
      - 11.6 The Spanish-American War: us-history/worksheets/11.6-the-spanish-american-war.md
      - 14.1 Rise of Aggressive Dictators: us-history/worksheets/14.1-rise-of-aggressive-dictators.md
      - 15.3 The Cold War Intensifies: us-history/worksheets/15.3-the-cold-war-intensifies.md
      - 15.4 Cold War Fears at Home: us-history/worksheets/15.4-cold-war-fears-at-home.md
    - 13 Readings: us-history/13-readings.md
    - 14 Savaas: us-history/14-savaas.md
    - Frederick Douglass Primary Source Reading: us-history/frederick-douglass-primary-source-reading.md
    - Reconstruction Webquest: us-history/reconstruction-webquest.md
    - Slavery DBQ: us-history/slavery-dbq.md
    - The Civil Rights Era: us-history/the-civil-rights-era.md
    - Vietnam War Webquest: us-history/vietnam-war-webquest.md
theme:
  name: material
  logo: assets/cca.png
  favicon: assets/favicon.ico
  features:
    - toc.follow
    - navigation.top
    - content.code.copy
    - content.action.edit
    - content.action.view
    - navigation.footer
    - content.tabs.link

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - glightbox
  - offline
  - social

markdown_extensions:
  - abbr
  - admonition
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.keys
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true


extra_javascript:
  - javascripts/katex.js
  - javascripts/kotlin.js
  - https://unpkg.com/kotlin-playground@1
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

extra_css:
  - stylesheets/kotlin.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
