name: Build Documentation

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3
          cache: pipenv
      - run: python3 -m pip install --upgrade pip pipenv
      - run: pipenv sync
      - name: Build Documentation
        run: pipenv run mkdocs build
